name: Authorize a new App to be automatically deployed

on:
  pull_request:
    types: [ opened, synchronize, labeled ]
    branches:
      - main
      - master
        
jobs:
  check_deploy_label:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy_app') }}
    steps:
      - run: echo "Contains label deploy_app"
  
  deploy:
    needs: [check_deploy_label]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.sha }}
        id: auth
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Analyze files that changed
        run: |
          echo "All:"
          echo "${{ steps.files.outputs.all }}"
          
          for changed_file in ${{ steps.files.outputs.all }}; do
            app_dir=${changed_file:9}
            key=${{ github.actor }}
            echo "Changed: $app_dir"
            
            if [[ "$app_dir" =~ ^$key.* ]]; then
              is_kind=${app_dir: -5}
              if [ "$is_kind" == ".kind" ]; then
                echo "ends with .kind"
              else 
                echo "A file that is not .kind changed."
                exit 1
              fi
            else
              echo "Something outsite the base/App/$key changed."
              exit 1
            fi
            
          done

  
